# Generated by Django 5.1.7 on 2025-03-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='title',
            field=models.CharField(max_length=245),
        ),
    ]
